### ISSUE TITLE
Do you have a performance test application?

### ISSUE THREAD

**Issue by csfreebird** [sewenew/redis-plus-plus#10]
since this project is well documented and have good features. A test application is necessary for all new people.

Thanks again, this project looks nice.

**Comment by sewenew** [comment]
Hi @csfreebird 

*redis-plus-plus* runs as fast as *hiredis*, since it's based on *hiredis*, and just forwards commands to *hiredis* to do the real work.

However, your point is great, and I'll add a benchmark test.

Regards

**Comment by sewenew** [comment]
Hi @csfreebird 

I've added a benchmark test application. Please see the [doc](https://github.com/sewenew/redis-plus-plus#performance) on how to run the benchmark test.

Also I refactored the test code, so that you can run tests without Redis Cluster.

If you only want to run tests with Redis, you only need to specify host, port and auth options:

```
./compile/test/test_redis++ -h host -p port -a auth
```

Regards

**Comment by csfreebird** [comment]
Thanks.
