### ISSUE TITLE
cmake on Windows

### ISSUE THREAD

**Issue by pasjkeee** [sewenew/redis-plus-plus#106]
Hello, I'm Rusian student from MPEI.
I was given the task to write an essay on libraries in C++ on Redis on Windows.
But I have no idea how to do it with cmake with this project on windows

**Comment by sewenew** [comment]
It should be easy to build redis-plus-plus with Visual Studio 2017 and 2019. Because since Visual Studio 2017, Visual Studio has built-in CMake supports, and you can check [this](https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/) and [this](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2017) for how to build a CMake project with Visual Studio 2017.

**NOTE**: You must install *C++ CMake tools for Windows* when installing Visual Studio.

With Visual Studio 2019, even better, you can clone and build a CMake project on GitHub easily. Check [this](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-open-project-from-repo?view=vs-2019) link for detail.

In the case of building redis-plus-plus, first of all, you need to build and install hiredis with the above method, then you can build redis-plus-plus. Since redis-plus-plus depends on hiredis, you also need to modify CMakeLists.json file to set *HIREDIS_HEADER*, *HIERDIS_LIB* and *HIERDIS_STATIC_LIB* to specify the installation path of hiredis headers, installation path of hiredis dynamic library and installation path of hiredis static library.

In fact, I'm not very familiar with Visual Studio, hope the above instructions helps.

Regards

**Comment by pasjkeee** [comment]
Ok, thank you. I'll try to do it right now.

**Comment by pasjkeee** [comment]
Your answer helped me a lot.
I have installed hiredis, using Ms VS 2019. But when installing redis plus plus, it started giving errors. But when installing using cmake with windows command line
<img width="957" alt="0" src="https://user-images.githubusercontent.com/72603507/95635773-062e4580-0a96-11eb-97c7-8d42c3e61cb2.PNG">
%my_directory_cmake.exe% .. -DHIREDIS_STATIC_LIB=".my_directory_hiredis.\hiredis\out\Debug\hiredis_static.lib" -DHIREDIS_LIB=".my_directory_hiredis.\hiredis\out\Debug\hiredis.lib" -DHIREDIS_HEADER=".my_directory_hiredis.\hiredis"
Everything went well, I got the redis++.lib and redis++_static.lib libraries.
But when building my project for my examples, after connecting the "h" and "lib" files, I get a linker error
<img width="397" alt="1" src="https://user-images.githubusercontent.com/72603507/95635715-d8490100-0a95-11eb-9083-dc5e0b374973.PNG">
My header files which I enabled
<img width="484" alt="3" src="https://user-images.githubusercontent.com/72603507/95635860-47bef080-0a96-11eb-84aa-6d3f0ae18985.PNG">
Libraries
<img width="477" alt="4" src="https://user-images.githubusercontent.com/72603507/95635970-98cee480-0a96-11eb-8b6d-2b61c0eb3a29.PNG">
<img width="465" alt="5" src="https://user-images.githubusercontent.com/72603507/95636007-b3a15900-0a96-11eb-8075-b1b39d321f78.PNG">

https://github.com/pasjkeee/RedisPMyexample my project
https://github.com/pasjkeee/mytestredisplusplus project redis plus plus

**Comment by pasjkeee** [comment]
All problems solved. Everything worked. Thank you very much!!!!!!!
