### ISSUE TITLE
Lambda Callback fails to launch

### ISSUE THREAD

**Issue by pfpRoboMan** [sewenew/redis-plus-plus#109]
Hey, 

Below is a simplified version of my code. It contains Thread1 for publishing messages and Thread2 for subscribing and processing the messages on two Redis channels. 

The threads execute without error, however the `sub.on_message([](std::string channel, std::string msg)` callback function in Thread2 does not successfully get called.

Any help is welcome as I am stumped...

Here is the code:

```
void Thread1()
{	
	try {
		ConnectionOptions opts;
		opts.host = REDIS_HOST; // Globally defined
		opts.port = REDIS_PORT; // Globally defined
	
		auto redis = Redis(opts);		

		// Redis Channel IDs
		std::string ch1 = "ch1";
		std::string ch2 = "ch2";

		/* Redis Publish/Subscribe Simulation loop */
		try {
			std::stringstream sbuf;
			
			sbuf << "Some data on " << ch1 ;
			redis.command("PUBLISH", ch1, sbuf.str());
			sbuf.str("");

			sbuf << "Some data on " << ch2;
			redis.command("PUBLISH", ch2, sbuf.str());
			sbuf.str("");
		}
		catch (const Error &err) {
			std::cerr << err.what() << std::endl;
		}
	}
	catch (const Error &err) {
		std::cerr << err.what() << "more info" << std::endl;
	}	
}


void Thread2()
{	
	try {
		ConnectionOptions opts;
		opts.host = REDIS_HOST; // Globally defined
		opts.port = REDIS_PORT; // Globally defined

		auto redis = Redis(opts);

		auto sub = redis.subscriber();

		// Setup callback lambda function - Process message of MESSAGE type
		sub.on_message([](std::string channel, std::string msg)
		{			
			if (channel.find("ch1") != std::string::npos)
			{							
				std::cout << msg << "on" << channel << std::endl;
				// some more processing...
			}

			if (channel.find("ch2") != std::string::npos)
			{
				std::cout << msg << "on" << channel << std::endl;
				// some more processing...
			}			
		});

		// Redis Channel IDs
		std::string ch1 = "ch1";
		std::string ch2 = "ch2";				

		// Redis Channel Subscribers
		sub.subscribe(ch1);
		sub.subscribe(ch2);

		/* Redis Subscribe Simulation loop */
		int numSubs = 2; 
		while (fn != (numSubs)) {
	//while (1) {
			try {
				sub.consume();
			}
			catch (const Error &err) {
				std::cerr << err.what() << std::endl;
			}
		}

		// Cleanup
		sub.unsubscribe();
	}
	catch (const Error &err) {
		// Error handling.
		std::cerr << err.what() << "more info" << std::endl;
	}
}
```

**Comment by sewenew** [comment]
@pfpRoboMan There're two possible reasons that your `on_message` callback were not called.

1. Thread1 runs faster than Thread2, and those 2 messages has already been published to Redis before Thread2 subscribes to the channels. In this case, these 2 messages are lost forever, and Thread2 can never receive these messages.

2. Does `fn` in your code, be a counter? And you want to consume these 2 messages and exit the while loop? In this case, you need to increment the counter in `on_message` callback, not in the while loop. Because when a subscriber successfully subscribes to a channel, Redis will [publish a meta message to the channel](https://github.com/sewenew/redis-plus-plus#subscriber-callbacks). However you did not register any callback for these meta message, so `Subscriber::consume()`  receives these meta message, and discard them. You only call `Subscriber::consume()` twice, and these calls, in fact, only consume the meta messages. So even if Thread1 runs slower than Thread2, these published messages won't be consumed, since you already exit the while loop.

Regards

**Comment by sewenew** [comment]
@pfpRoboMan Since there's no new reply from you, I'll close this issue. If you still have problem with it, feel free to reopen it.

**Comment by pfpRoboMan** [comment]
All clear - Thanks for your help 👍
