### ISSUE TITLE
pipelining support

### ISSUE THREAD

**Issue by ashwani29** [sewenew/redis-plus-plus#117]
Does redis-plus-plus support pipeline i.e. executing multiple commands without waiting for response for each ?

**Comment by sewenew** [comment]
redis-plus-plus supports [Redis pipeline](https://redis.io/topics/pipelining). However, I'm not sure if Redis pipeline is what you want. Redis pipeline is used to *send multiple commands to the server without waiting for the replies at all, and finally read the replies in a single step*, so that it can reduce RTT.

Regards

**Comment by ashwani29** [comment]
Hi, I wanted to build a custom redis-client which will not wait for the response but keep sending requests to the server, on redis site I came to know that there is redis-pipeline thing which can help, I'm new to this redis, if you have some more information about whether this can be achieved or what similar goal can be achieved regarding this, then please share. 

According to your above reply, it seems I have to have read the response after sending multiple commands in a single pipeline.

**Comment by sewenew** [comment]
Yes, with Redis pipeline, you need to read all responses after sending these commands.

If you don't read the responses, how do you know that your commands have been sent to Redis successfully?

I think there're two possible solution that might achieve your goal:

- Send these command with Redis pipeline, and read all responses in another thread, so that your main thread doesn't need to wait for these responses.
- Use an asynchronous client to send command to Redis to avoid wait the response in your main thread.

Regards
