### ISSUE TITLE
Could support be added for `zadd XX INCR`?

### ISSUE THREAD

**Issue by rjhann** [sewenew/redis-plus-plus#120]
The documentation for redis++ `Redis::zadd` claims
> We don't support the INCR option, since you can always use ZINCRBY instead.

However, due to the `XX` option this is not quite true; it is supported by [redis `ZADD`](https://redis.io/commands/zadd) but not [redis `ZINCRBY`](https://redis.io/commands/zincrby), which always adds new elements to the set if they don't exist.

Could support for this be added to the `Redis::zadd` interface?

A small example confirming redis does allow `ZADD XX INCR`:

```
$ redis-cli 
127.0.0.1:6379> zrange test-zset 0 -1 WITHSCORES
(empty array)
127.0.0.1:6379> zadd test-zset XX INCR 10 test-thing
(nil)
127.0.0.1:6379> zrange test-zset 0 -1 WITHSCORES
(empty array)
127.0.0.1:6379> zincrby test-zset 10 test-thing
"10"
127.0.0.1:6379> zrange test-zset 0 -1 WITHSCORES
1) "test-thing"
2) "10"
127.0.0.1:6379> zadd test-zset XX INCR 10 test-thing
"20"
127.0.0.1:6379> zrange test-zset 0 -1 WITHSCORES
1) "test-thing"
2) "20"
```

**Comment by sewenew** [comment]
@rjhann Thanks for pointing out the problem! Yes, it's my mistake, and the comment is incorrect.

Another reason that I didn't add `INCR` support is because normally the return value of `zadd` is of `long long`, however, when `INCR` is specified, the return value of `zadd` command is of string type. C++ doesn't allow overload by return value, so we have to define a method named something like `zadd_incr`. I'm not sure if this is an elegant solution.

However, you can always use the [generic interface](https://github.com/sewenew/redis-plus-plus/#generic-command-interface) to send any command, including `zadd` with `INCR` option:

```
auto redis = Redis("tcp://127.0.0.1");
auto score = redis.command<Optional<double>>("zadd", "test-zset", "XX", "INCR", 10, "test-thing");
if (!score) {
    cout << "not exist" << endl;
} else {
    cout << "new score: " << *score << endl;
}
```

I think this generic interface should solve your problem. If you still have any problem on it, feel free to let me know :)

Regards

**Comment by sewenew** [comment]
The incorrect comment has been fixed.
