### ISSUE TITLE
Redis version for test

### ISSUE THREAD

**Issue by snlv182** [sewenew/redis-plus-plus#131]
![image](https://user-images.githubusercontent.com/60073285/102855513-bf7aa580-445f-11eb-8e50-64760c530140.png)

Hi,
 now, it is still only work for Redis 5 ?

my redis version is :

![redis-version](https://user-images.githubusercontent.com/60073285/102855661-0799c800-4460-11eb-939f-df088ad5e6f3.png)
![redis-version](https://user-images.githubusercontent.com/60073285/102855697-12ecf380-4460-11eb-9363-925db05bee70.png)
Thanks.

**Comment by sewenew** [comment]
@snlv182 Yes, the test only works for Redis 5.0 or later. It cannot pass all tests for Redis 3.2.9.

Because the test will try to send some command that's only supported by Redis 4.x and Redis 5.x. If you're using an older version, the Redis server won't response with a correct response, and the test will fail.

However, don't worry about the test. Redis ensures that protocol is compatible with old version. Redis-plus-plus has been full tested, and you can use redis-plus-plus to send command to old version of Redis.

Regards

**Comment by snlv182** [comment]
Ok, got it. So, until now, for tests, they  still only can be used  for Redis 5.0+
but except test, for all Redis version, it can all support~~
Thanks.

**Comment by sewenew** [comment]
Yes, you're right! It works for all Redis version.

Regards

**Comment by snlv182** [comment]
yep, got it, Thank you very much~~
