### ISSUE TITLE
Redis cluster with core dump 

### ISSUE THREAD

**Issue by gaofeia** [sewenew/redis-plus-plus#137]
When I use redis cluster in multiple threads, core sump appears 。The error may occur when creating the object or when ’brpop‘。I also tried to create its object in the process with create multiple connections in the connection pool, reuse this object, but the same problem will also occur.
This is part of my code：

    ConnectionOptions connection_options;
    connection_options.host = myApp->m_strRddisIP;  // Required.
    connection_options.port = myApp->m_iRedisPort; // Optional. The default port is 6379.
    connection_options.password = myApp->m_strRedisPass; // Optional. No password by default.
    connection_options.socket_timeout = std::chrono::milliseconds(10);

    ConnectionPoolOptions pool_options;
    pool_options.size = 1;
    pool_options.wait_timeout = std::chrono::milliseconds(10);

    RedisCluster cluster(connection_options, pool_options);
   while(MyApp::s_bRun)
    {
        strValueList.clear();
        while(1)
        {
            optStrPair = cluster.brpop(strKey, 1);
            if(optStrPair)
            {
                strValueList.push_back(optStrPair.value().second);
            }
            else
            {
                //超时：没有数据超时返回
                break;
            }

            if(strValueList.size() >= iMaxLine)
                break;
        }
    ...
 }

**Comment by gaofeia** [comment]
the error ：
what():  Failed to send command with key:
what():  Aborted (core dumped)

**Comment by sewenew** [comment]
First of all, you should always try-catch possible exceptions thrown by redis-plus-plus, otherwise, your application will coredump:

```
try {
    // redis-plus-plus related code
} catch (const sw::redis::Error &e) {
    // error handle
}
```

In your case, you got the exception, because the socket timeout (10 milliseconds) you set is smaller than the timeout (1 second) you sent with `brpop` command. So before `brpop` returns, the socket will timeout, and redis-plus-plus throws exception.

In order to avoid the problem, you should set socket timeout larger than `brpop`'s timeout parameter.

```
connection_options.socket_timeout = std::chrono::seconds(10);    // timeout is 10 seconds

// other code

optStrPair = cluster.brpop(strKey, 1);       // timeout is 1 second
```

Please check the [doc](https://github.com/sewenew/redis-plus-plus#connection) for detail.

Regards
