### ISSUE TITLE
Can I use "CLIENT TRACKING ON .." command?

### ISSUE THREAD

**Issue by dkd1111** [sewenew/redis-plus-plus#139]
I can't know ID of subscriber object(connection).

- CLIENT TRACKING ON REDIRECT "ID" 

This command needs client id of subscriber.
How can I do for using the command?

**Comment by sewenew** [comment]
It seems that you're doing client side cache. So far, redis-plus-plus doesn't have built-in support for it. However, you can use the [generic command interface](https://github.com/sewenew/redis-plus-plus#generic-command-interface) to implement it by yourself, e.g. `redis.command<void>("CLIENT", "TRACKING", "ON", "REDIRECT", std::to_string(id))`.

In order to get the client id of current connection, you can use the `CLIENT ID` command: `auto id = redis.command<long>("client", "id");`

Regards

**Comment by dkd1111** [comment]
Redis creates ID per a connection.
In your codes, Redis::subscirber() create a connection. I can get "Subscriber" instance and its ID.
However, this instance does not have command function.
You mean I have to add command function to your codes? or I misunderstood?

**Comment by sewenew** [comment]
My bad! I misunderstood your question.

Yes, so far, there's no way to get the client id of a Subscriber. You have to change the code to implement a customized Subscriber. Sorry for that.

Regards

**Comment by dkd1111** [comment]
Thanks for your replies.

Do you have a plan that generic command interface is implemented for subscriber class?
I want to keep the latest version. This project is actively so far.
I should merge your codes if I customize the codes.

**Comment by sewenew** [comment]
No, there won’t be a generic command for Subscriber. Because Redis doc specifies:

> The commands that are allowed in the context of a subscribed client are SUBSCRIBE, PSUBSCRIBE, UNSUBSCRIBE, PUNSUBSCRIBE, PING and QUIT.

Since the commands are limited, there is no need to have generic command.

You should get the client id before sending subscribe command.

Regards

**Comment by dkd1111** [comment]
OK. thanks.
