### ISSUE TITLE
How to listen the key expired event ? 

### ISSUE THREAD

**Issue by yangjiechina** [sewenew/redis-plus-plus#154]
Hi sewenew.Redisplusplus is a great library,but i ran into a problem in using it.

I just want to listen the expired event，similar to the redis command `psubscribe__ keyevent@0__ :expired`.

I searched through the test source code and issues, but I couldn't find what I wanted.

what to do ?

my code :
`int main(){

    ConnectionOptions connect_options;

    connect_options.host = "192.168.0.157";
    connect_options.port = 6379;
    connect_options.db = 0;
    connect_options.socket_timeout = std::chrono::milliseconds(500);

    try{
        Redis r1(connect_options);

        // Create a Subscriber.
        auto sub = r1.subscriber();

        // Set callback functions.
        sub.on_message([](std::string channel, std::string msg) {
                    cout<< "on message " << msg <<endl;
                });

        sub.on_pmessage([](std::string pattern, std::string channel, std::string msg) {
                    cout << "on pmessage "<< msg << endl;
                });

        sub.on_meta([](Subscriber::MsgType type, OptionalString channel, long long num) {
                    cout << "on meta" << endl;
                });

        //sub.psubscribe("__keyevent@0__:expired");
        sub.psubscribe("expired");
        r1.set("redispp","test");
        r1.expire("redispp",10);
        r1.set("redispp2","test");
        r1.expire("redispp2",10);
        // Consume messages in a loop.
        while (true) {
            try {
                sub.consume();
            } catch (const Error &err) {
                cout << "Error" << endl;
            }
        }
    }catch(TimeoutError & e){
        cout << "connect error" <<endl;
    }
    

    getchar();
    return 0;
}`

**Comment by wingunder** [comment]
Hi @yangjiechina

I didn't try to compile or run your code, but I think your problem is in the following line:
```
sub.psubscribe("expired");
```
Try changing it to:
```
sub.psubscribe("*expired");
```
[psubscribe](https://redis.io/commands/psubscribe) is for a pattern.
You can also use the plain [subscribe](https://redis.io/commands/subscribe), without a pattern, but then you'll have to pass your complete key name. Like this:
```
sub.subscribe("__keyevent@0__:expired");
```
BTW, there is an example for this. Take a look at the following:

https://github.com/sewenew/redis-plus-plus/blob/fcb44a8c131d4d806775abdd10192cb8c1965421/test/src/sw/redis%2B%2B/pubsub_test.hpp#L123-L145

I hope that this could have helped you.
Regards

**Comment by yangjiechina** [comment]
Thank you for your reply.I use the first two methods:`sub.psubscribe("*expired")
``sub.subscribe("__keyevent@0__:expired");
`.All successful
Thanks again and happy New Year.
