### ISSUE TITLE
hiredis install directory problem in Win10

### ISSUE THREAD

**Issue by perevertysh** [sewenew/redis-plus-plus#155]
Hey! Not use yet that lib, but  build it! Thanks a lot! Great work! 

There is some problem with configuring of redis++ for cmake. Problem was here:

> Since redis-plus-plus depends on hiredis, we need to specify the installation paths of hiredis before building it. You can use the Open Folder feature to open redis-plus-plus project. You need to edit the CMakeSetting.json file (automatically generated by Visual Studio) to set HIREDIS_HEADER, HIREDIS_LIB and HIREDIS_STATIC_LIB variables to specify the installation path of hiredis headers, installation path of hiredis dynamic library and installation path of hiredis static library. The following is an example of CMakeSetting.json file:

HIREDIS_HEADER!

When build it with VS2019 there is C1083 error like: 
hiredis/hiredis.h not found

It fixed with adding hiredis source files to **src/sw/redis++/hiredis** dir. 

P.S.: It will be great, if somebody add explanation of usage with  QT projects.

**Comment by wingunder** [comment]
Hi @perevertysh

I think you might not have followed the [installation instructions](https://github.com/sewenew/redis-plus-plus#installation). It clearly states that you should install `hiredis` first. If you don't do this, <hiredis/hiredis.h> won't be found and secondly, you'll probably end up with a linking problem, as the hiredis library won't be available either. So, please first install 'hiredis'.

I only develop under Linux, so unfortunately I can't help you any further with VS2019.
For your QT question, please try stackoverflow or similar.
Regards

**Comment by sewenew** [comment]
@perevertysh As @wingunder mentioned, you should build and install hiredis first, since redis-plus-plus depends on it.

It seems that you're using VS2019, it should be very easy to build it by downloading the source code of hiredis, and build and install it with the *Open Folder* feature (File -> Open -> Folder) of VS 2019 (Build -> Install hiredis). Normally hiredis should be installed at */path/to/hiredis/out/install/x64-Debug*. In this directory, you should find the headers, dynamic libraries and static libraries. Then you can specify the paths in CMakeSetting.json, as I mentioned in the doc.

Also, Vcpkg has support for [installing redis-plus-plus on Windows](https://github.com/microsoft/vcpkg/pull/14180). This should be a much easier way to install both hiredis and redis-plus-plus. You can have a try.

I'm not an expert on Visual Studio and QT, if you still have problems with it. Please take @wingunder 's suggestion to ask help with some experts.

Also thanks for choosing redis-plus-plus :)

Regards
