### ISSUE TITLE
How to use the command interface to set client name?

### ISSUE THREAD

**Issue by patrickjchen** [sewenew/redis-plus-plus#168]
Hi,  I was trying to use the following code to set client name, but seems it did not work. Nothing printed when try to get it back with "getname".  Could you please help? Thanks.  
---Patrick
 redis.command<OptionalString>("client","setname","xyz");
 auto val = redis.command<OptionalString>("client", "getname");
 if (val) {
        std::cout << *val << std::endl;
 }

**Comment by patrickjchen** [comment]
Just found out that with a plain Redis connection, I could use script_flush(). However, the same method does not exist for RedisCluster. How to do the same thing (client setname) for a RedisCluster client? Thanks.
---Patrick

**Comment by sewenew** [comment]
> Hi, I was trying to use the following code to set client name, but seems it did not work. Nothing printed when try to get it back with "getname". Could you please help? Thanks.

You should specify the return value type as template parameter of the `command` method:

```
redis.command<void>("client","setname","xyz");
auto val = redis.command<OptionalString>("client", "getname");
if (val) {
    std::cout << *val << std::endl;
}
```

Regards

**Comment by sewenew** [comment]
> However, the same method does not exist for RedisCluster. How to do the same thing (client setname) for a RedisCluster client? 

`RedisCluster` does not support commands or Lua scripts that have no key as parameter, since it has no idea on which node these commands should be sent. Please check the [doc](https://github.com/sewenew/redis-plus-plus#interfaces) for detail.

```
auto r = cluster.redis("your-key");
r.script_flush();
```

However, so far, there's no easy way to send these command to all nodes in the cluster, since you need to know a hash tag for each node. I'll fix this in the future. Currently, if you want to send script_flush to all commands, you can create a `Redis` object for each node, and send command with these objects.

Regards

**Comment by patrickjchen** [comment]
Many thanks!
