### ISSUE TITLE
Thread Safety of Pipeline

### ISSUE THREAD

**Issue by gajjarvini** [sewenew/redis-plus-plus#176]
Hi @sewenew,
I really appreciate the library and I am glad to use it. 

I have been using the Pipeline feature in my project which is multi-threaded. From the project wiki, it is understood that Pipeline member functions are not thread safe and they require synchronization in order to be called from different threads.

And so could you please help me understand the following scenario.

If the scope of the Pipeline object is limited to a function, and every time a thread tries to call the function a new Pipeline object is created. So in easy words multiple threads calling the function will have their own independent Pipeline object. No thread will be sharing a single Pipeline object.
**The question is : In this case when each thread has its own independent Pipeline object, is it still required for the threads to synchronize when calling the member functions of their own individual Pipeline object ?**

Thank you,
Regards,
Vini

**Comment by sewenew** [comment]
If I understand correctly, you have code like the following:

```
void func(sw::redis::Redis &redis) {
    try {
        auto pipe = redis.pipeline();
        auto res = pipe.set("key", "val").hset("hash", "field", "val").exec();
        // other code
    } catch (const Error &) {
    }
}
```

And multiple threads might call this `func` concurrently, right?

In this case, it's thread-safe. You don't need to do synchronization work, since each thread operates on a different Pipeline object, and creating a `Pipeline` object, i.e. the `Redis::pipeline()`, is thread-safe.

However, the above code might be inefficient, since it creates a new connection for each call. In order to avoid creating new connection, you can check [this doc](https://github.com/sewenew/redis-plus-plus#create-pipeline-without-creating-new-connection) for detail. Also, be sure to read the doc carefully before this optimization, otherwise, you might get other problems, e.g. dead lock.

Regards

**Comment by gajjarvini** [comment]
Yes, I have code similar to the above example that you have provided and yes, multiple threads may call that function concurrently.

Referring to the document previously, I am already passing "false" explicitly to ensure that the pipeline uses the available connections from the underlying pool and does not create a new one whenever the function is called.
Thank you for providing an example on deadlock in the document.

I appreciate your prompt response,
Regards,
Vini Gajjar
