### ISSUE TITLE
Problem with cluster xreadgroup block

### ISSUE THREAD

**Issue by bip21** [sewenew/redis-plus-plus#178]
Hello,

We have got a problem when using xreadgroup with "block" in a cluster environment.

When we call the RedisCluster::xreadgroup method without timeout and no data to retrieve there is no raising exception.
When we call it with a timeout and data no exception either (we retrieve the data correctly).
When we call it with a timeout and no data to retrieve it does not block and we have the exception "Failed to send command with key" systematically.
We tried the xreadgroup command with block with redis-cli and it works against the same cluster (it waited the requested time).

Do you any idea why it could not block?

Regards.

**Comment by sewenew** [comment]
Can you show me the code that can reproduce the problem?

Also have you set `ConnectionOptions::socket_timeout`? If you do, you must ensure that the `socket_timeout` is larger than the timeout parameter of `xreadgroup`, otherwise, you'll get exception. Check the **NOTE** part of the [connection doc](https://github.com/sewenew/redis-plus-plus#connection) for detail.

**Comment by bip21** [comment]
Thank you for your answer, you were right it was due to the socket_timeout.
I close this.
