### ISSUE TITLE
Does this lib support latest Hiredis?

### ISSUE THREAD

**Issue by Cactusinhand** [sewenew/redis-plus-plus#182]
It seems not.

When I compiled my project, it warns me that:
```bash
/usr/bin/ld: warning: libhiredis.so.0.13, needed by //usr/local/lib/libredis++.so, not found (try using -rpath or -rpath-link)
```
Hiredis releasenote said:
```
Release of v1.0.0
Hiredis v1.0.0 marks the first stable release of Hiredis 
```
so how to make it support the first stable release?

@sewenew 

Thanks!

**Comment by sewenew** [comment]
@Cactusinhand In fact, it's recommended to use the latest release of hiredis.

First of all, you must install hiredis manually before install redis-plus-plus. Also you must ensure that there's only 1 version of hiredis is installed, otherwise, you might get some wired problems.

Please check the `/usr/local/lib` directory, i.e. the default install path of hiredis, or use the `apt-get` related command to check if 1 and only 1 of hiredis version has been installed correctly.

Regards

**Comment by Cactusinhand** [comment]
Yes, I do install multi version of hiredis. and now the issue have been fixed \o/

Thanks!
