### ISSUE TITLE
ConnectionPool::fetch() holds mutex while establishing a new connection

### ISSUE THREAD

**Issue by gavllew** [sewenew/redis-plus-plus#192]
https://github.com/sewenew/redis-plus-plus/blob/df522812ba4114f1dd3386b81afc2369c82b717d/src/sw/redis%2B%2B/connection_pool.cpp#L76-L90

When a ConnectionPool is empty, but has not yet reached its maximum size, the `fetch()` method creates a new connection.  Unfortunately it currently holds the pool's mutex while this is created and established, which appears to be unnecessary.
 This blocks all other unrelated pool activity involving existing connections, or creation of additional new connections.

**Comment by sewenew** [comment]
Yes, the lock has performance penalty. However, it makes the code easier to write, since it seems that it's not an easy job to avoid the lock here.

In fact, as you mentioned, only when the pool is empty, and not yet reaches the maximum size, this code will have a performance penalty. In most cases, it won't be a problem.

Anyways, thanks for your suggestion! I'll try to find an easy way to avoid the lock in the future.

Regrads

**Comment by sewenew** [comment]
The problem has been fix with this [pr](https://github.com/sewenew/redis-plus-plus/pull/422).

Regards
