### ISSUE TITLE
redis-plus-plus fails to compile if prior to it's include the code includes <windows.h> and / or <shlwapi.h>

### ISSUE THREAD

**Issue by orennitzan** [sewenew/redis-plus-plus#194]
Hi,
This is a nasty one. 
I spent 3 days on it.
The problem:
When I include redis-plus-plus after some include that has, down the line   includes of <windows.h> and / or <shlwapi.h>
The project will not compile and give errors like i forgot to put semicolon somewhere.
When commented it compiles fine.
When redis-plus-plus is included before those, also everything is fine.

// This is fine
#include <sw/redis++/redis++.h>
#include <windows.h>

// This will breake
#include <windows.h>
#include <sw/redis++/redis++.h>

Any idea? 
Thanks

**Comment by sewenew** [comment]
@orennitzan I did some research, and it seems that the root cause is we must ensure to include *winsock2.h* before *windows.h*.

*hiredis* depends on `timeval` struct, and on Windows platform, this struct is defined in *winsock2.h*. So redis-plus-plus [includes this header](https://github.com/sewenew/redis-plus-plus/blob/1.2.3/src/sw/redis++/connection.cpp#L27). However, there's some problem with *winsock2.h* and *windows.h* files, and we must ensure that *winsock2.h* is included before *windows.h*, otherwise, you'll get some wired errors. Please check the following links for reference: 

- [winsock2.h include order](https://sourceforge.net/p/mingw-w64/wiki2/winsock2.h%20include%20order/#:~:text=Solution%3A%20If%20you%20want%20to%20use%20the%20winsock2,make%20sure%20that%20you%20have%20the%20correct%20header.)
- [C++ Redefinition Header Files](https://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h)
- [Cannot include both files WinSock2, Windows.h](https://stackoverflow.com/questions/21399650/cannot-include-both-files-winsock2-windows-h)

Thanks for pointing this out! I'll add some document for this problem.

Regards

**Comment by orennitzan** [comment]
#define NOMINNMAX
See: https://stackoverflow.com/questions/16181132/hundred-errors-while-including-windows-h

**Comment by orennitzan** [comment]
Thanks a lot sewnew.
