### ISSUE TITLE
#if __cplusplus >= 201703L

### ISSUE THREAD

**Issue by paceholder** [sewenew/redis-plus-plus#248]
Hello!

https://github.com/sewenew/redis-plus-plus/blob/80395ec098141cd10d5f665cbca1b2605e1643ab/src/sw/redis%2B%2B/utils.h#L21
I think the line above is not quite correct.
It just indicates that the compiler supports the `C++17` standard but this does not imply that the main application code is going to be compiled using `C++17`.

And other way round: I tried to use precompiled libraries available on `conan.io` and it turned out that they were built with something pre-`c++17`. In my application I do use this standard. During compilation I got a linking error because of the discrepancy between what has been compiled and what has been evaluated during including the `redis-plus-plus` header:
```
undefined reference to `sw::redis::Redis::hget[abi:cxx11](std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&)'
```
Maybe a work-around could be some pre-defined compile-time constant?

```
#if __cplusplus >= 201703L && REDIS_PLUS_PLUS_COMPILED_WITH_CPP17
```

Thanks  && best regards

Dmitry

**Comment by sewenew** [comment]
Hi @paceholder,

Sorry for the inconvenience, but add another macro, e.g. REDIS_PLUS_PLUS_COMPILED_WITH_CPP17, is not a good idea. Since the application code have to be compiled with this macro, that's a burden for the application code.

I'll make C++ 17 as the default standard in the next release, since it's already 2021.

Regard

**Comment by paceholder** [comment]
Thanks for the answer.
I managed to hoop up with the library as a git-submodule and defined a cmake variable `REDIS_PLUS_PLUS_CXX_STANDARD = 17`.
This helped me to both build the library with the chosen standard and then compile my project with 17 as well.

**Comment by vcampmany** [comment]
I have the same problem, also using the package from `conan.io`. As a workaround I added the following line in my conan profile file:
```
redis-plus-plus:compiler.cppstd=17
```
In this case, the package will be built from source, because as you said, there is no precompiled version of it. Hope this is helpful @paceholder 

@sewenew do you know when will the next release be ready?

**Comment by sewenew** [comment]
@vcampmany I’ll release it with async interface. I’m still working on it. I think it could be released next week.

Regards

**Comment by sewenew** [comment]
Hi all,

Sorry but I forget to tell you that the code has been released. Now redis-plus-plus is built with C++ 17 by default.

Regards
