### ISSUE TITLE
Creating a redis-plus-plus type event when a hash slot moves.

### ISSUE THREAD

**Issue by wingunder** [sewenew/redis-plus-plus#249]
Hi @sewenew

As we know, Redis does not support any events when hash slots move, with Redis Cluster.
However, we could get notified of this when we build some hooks into the following function. Would it be possible to add something like this inside redis-plus-plus, every time `_pool.update()` is being called?

I have not given any thought on how these events/hooks could be implemented. I just wanted to know if this could be an idea for an addition to redis-plus-plus? Or maybe there's even a better idea, that I have missed up to now.

Regards

https://github.com/sewenew/redis-plus-plus/blob/eff34aa7783d38940a9ad51263e1595fcd71ec01/src/sw/redis%2B%2B/redis_cluster.hpp#L1331-L1372

**Comment by sewenew** [comment]
Hi @wingunder 

> However, we could get notified of this when we build some hooks into the following function. Would it be possible to add something like this inside redis-plus-plus, every time _pool.update() is being called?

This is not a perfect solution. `_pool.update()` is called, only when you read/write a key which has been moved. However, if your code does not read/write keys in the moved slot, this method won't be called, and you cannot be notified.

> I have not given any thought on how these events/hooks could be implemented. I just wanted to know if this could be an idea for an addition to redis-plus-plus? Or maybe there's even a better idea, that I have missed up to now.

If some slot is moved, there must be a `CLUSTER SETSLOT` command. So you can call the MONITOR command on every node of the cluster. If one of the client monitors a `CLUSTER SETSLOT` command, there must be a slot move operation. However, this method is also not good enough, since the `MONITOR` command slow down Redis.

Another solution is that you can send `CLUSTER SLOTS` command at regular intervals, and check if the slots info has been changed.

Regards

**Comment by wingunder** [comment]
Hi @sewenew 

Thanks for your answer. The problem that I'd like to solve, is the following:

I have 2 (or more) normal Redis servers, independently running the same software with the same input (a kind of hot backup). This means that the content of the Redis servers are theoretically the same, except for minor timing differences.  It would of course be much better to have a Redis cluster and have worker processes that are distributed over the 2 or more servers. The entire software is already migrated to use redis-plus-plus and the switch-over to Redis cluster works out of the box, thanks to redis-plus-plus. This is great!

The problem is now to properly get the worker processes to run on all servers and let them automatically do the work without skipping things or doing things twice. There are many ways to do this. Using Redis streams with consumer groups is one, but is not an option, as the data needs to be handled sequentially, so parallelizing won't work. At the moment workers subscribe and do the work when they get data. The simplest route will be to keep this strategy, however the workers should then know if they should act on data or not. An easy way to do this would be to find out, from which Redis cluster-node the data came. This is why I'd like to know when a key moves. This way the workers can know if they need to do work for a certain key or not, depending where the node has moved to.

The `_pool.update()` solution would in this case work well, as no other software interferes with it, and as it's all using redis-plus-plus. Another reason for using this solution is that the writes are triggered by the workers, so a constant polling of `CLUSTER SLOTS` or monitoring of the `CLUSTER SETSLOT` command is not needed. A hook in `_pool.update()` will most probably be enough in this case.

For now, I'll follow your suggestion of polling `CLUSTER SLOTS`.
Thanks for the tips.

Regards

**Comment by sewenew** [comment]
Hi @wingunder 

Sorry, but I'm not quite understand your scenario. Can you give some concrete example of your scenario.

If you just want ensure the input will be processed by more than one worker process (for backup), you can use Redis Stream, and each work process has it own group id. So that they will consume the same input, and since there's only one consumer in the group, they will consume the inputs sequentially. It seems that you even don't need to use Redis Cluster. Correct me, if I'm wrong.

Regards

**Comment by wingunder** [comment]
Hi @sewenew 

Yes actually you are right about the sequential consumption of consumer groups. I had a look at it again and I can certainly use that to solve this problem.
Thanks a lot for your help.

Regards
