### ISSUE TITLE
[Question] Use Redis as class property

### ISSUE THREAD

**Issue by WoodySlum** [sewenew/redis-plus-plus#27]
Hi,

I would like to use Redis instance as class property, but didn't succeed yet.

.h
```
#include <sw/redis++/redis++.h>

class MemoryStorage {
    public:
        MemoryStorage(bool throwException);
        ~MemoryStorage();
    private:
        sw::redis::Redis mRedis;
};
```

.cpp

```
#include "MemoryStorage.h"

MemoryStorage::MemoryStorage(bool raiseExceptions) {
    this->rconnect(raiseExceptions);
}

MemoryStorage::~MemoryStorage() {
    
}

void MemoryStorage::rconnect(bool raiseExceptions) {
    this->mRedis = new sw::redis::Redis("tcp://127.0.0.1:6379");
}
```

You know what's wrong ?

**Comment by sewenew** [comment]
`mRedis` is an object, NOT a pointer. And, you're trying to assign it with a pointer, i.e. `this->mRedis = new sw::redis::Redis("tcp://127.0.0.1:6379");`.

In order to make the code compile, you need to define `mRedis` as a pointer, i.e. `sw::redis::Redis *mRedis;`, and delete it in the destructor. Also, a better way is to define `mRedis` as a `unique_ptr<sw::redis::Redis>`.

**Comment by WoodySlum** [comment]
Thanks for helping, now it's ok !
