### ISSUE TITLE
specify "target" host with redis cluster

### ISSUE THREAD

**Issue by Strafo** [sewenew/redis-plus-plus#271]
Hi,
I am using redis++ with redis cluster and the RedisTimeSeries module.
The TS.MRANGE command when used on a node that does not contain the data unfortunately returns (empty array) instead of MOVED.  (https://github.com/RedisTimeSeries/RedisTimeSeries/issues/368#issuecomment-602630418)

I therefore thought of solving the problem by running the EXIST command and then going to retrieve the data.

Given an instance of RedisCluster, can I specify on which node to execute the command?

**Comment by Strafo** [comment]
soution:
https://github.com/RedisTimeSeries/RedisTimeSeries/issues/854#issuecomment-924822294

**Comment by sewenew** [comment]
If you already has the IP and port info for a given node, you can create a `Redis` object instead of `RedisCluster` object.

Also, if you know the hash-tag of the node, you can use `RedisCluster::redis(const StringView &hash_tag, bool new_connection = true)` to create a connection to the node that contains the given hash tag.

Regards
