### ISSUE TITLE
[QUESTION] Why are the `auth`, `echo` and `ping` commands not available for RedisCluster?

### ISSUE THREAD

**Issue by wingunder** [sewenew/redis-plus-plus#309]
Hi @sewenew,

Is there any particular reason why the `auth`, `echo` and `ping` commands are not available for `RedisCluster`.

I am busy doing a migration to `RedisCluster` on some existing software, and I am missing the `ping` command for `RedisCluster`. For now, I am using:
```C++
auto reply = command(cmd::echo, msg);
```
It would however have been nice to just have had `Redis` and `RedisCluster` as compatible as possible. Like this a migration from `Redis` to `RedisCluster` is very simple. BTW, I know that due to the `keys`, `scan`, etc. commands a 100% compatibility is of course impossible.

If there is no particular reason why the `auth`, `echo` and `ping` commands are not available for `RedisCluster`, I could quickly make a patch to add them.

I am still amazed at just how easy it is, to just swap out the `Redis` class with `RedisCluster`, by means of a C++ template. Wonderful!

Regards

**Comment by wingunder** [comment]
Hi @sewenew,

I'm sorry, but two parts of my previous message was _not_ correct:

Firstly, my work-around is not:
```C++
auto reply = command(cmd::echo, msg);
```
It is instead:
```C++
RedisCluster redisClusterInstance(connOpts);

auto redisInstance = redisClusterInstance.redis("some_string");
bool success = (redisInstance.ping() == "PONG");
```

And secondly:
> If there is no particular reason why the `auth`, `echo` and `ping` commands are not available for RedisCluster, I could quickly make a patch to add them.

I had a closer look, and this is definitely not going to be a quick and easy change.

I also realized that "pinging a Redis server" is not the same as "pinging a cluster". 
"Pinging a cluster" could be in one of many different forms:
   - ping any node of the cluster
   - ping any master of a cluster
   - ping all nodes of a cluster
   - ping all masters of a cluster
   - ping the currently connected cluster node

The last form, 'ping the currently connected cluster node', could probably be the easiest to implement. It's allso the one that makes the most sense, as that is what `redis-cli` does.

Regards

**Comment by sewenew** [comment]
@wingunder Yes, as you mentioned, ping/echo a Redis instance is different from ping/echo a cluster.

> The last form, 'ping the currently connected cluster node', could probably be the easiest to implement.

The problem is how to define **currently connected cluster node**.

```
auto redisInstance = redisClusterInstance.redis("some_string");  // 1st

auto another_redis = redisClusterInstance.redis();  // 2nd
```

In the code above, the 1st Redis object creates a connection to the node where *some_string* is located, where the 2nd object randomly choose a node, and create a connection to it.

Obviously we cannot use the 2nd one as **current node**, since it randomly chooses a node, even if we can ping it successfully, we've no idea on whether another ping will success (since it might randomly choose another one).

The 1st one requires user to specify a hash-tag, however, the API of ping/echo will be confusing:

```
string RedisCluster::ping(const StringView &str);
```

It's hard to tell whether `str` is a ping message, or a hash-tag.

That's why RedisCluster has a `redis` method to create a `Redis` object, so that user can send commands without key as parameter, with this `Redis` object.

> It's allso the one that makes the most sense, as that is what redis-cli does.

redis-cli specifies a port parameter to connect to a specific node, it works like `RedisCluster::redis(const StringView &hash_tag)`. Instead of port, `RedisCluster::redis` uses hash-tag to specify a node.

`auth` command is another story.

`Redis::auth` is deprecated. Because it randomly pick a connection from the connection pool, and send `AUTH` command to it. However, when user call another command, it might pick another connection which has not been authed. I did not realize this problem until `Redis::auth` has been published. That's why `RedisCluster::auth` is not implemented.

So instead of `auth`, user should use `ConnectionOptions::password` to set the password.

Regards

**Comment by wingunder** [comment]
Hi @sewenew 

Thanks for your detailed explanation.

I am closing this issue for now.

Regards
