### ISSUE TITLE
[FEATURE] Ability to set custom client name on subscriber session

### ISSUE THREAD

**Issue by Cezero** [sewenew/redis-plus-plus#316]
When the subscriber creates a new connection, it has a blank name.  This ultimately results in a bunch of client sessions on the Redis server that all have blank names and are hard to distinguish between.

Given that there is no interface to send commands on the "subscriber" connection, there is no way to call CLIENT SETNAME to modify the subscriber session's name.  Ideally I would like to be able to set the client name in connection_options and have that be applied to the Redis connection (either the main one, or a connection created by a call to subscriber()).  Alternatively, exposing a function subscriber.setName() or something similar that would call CLIENT SETNAME on the underlying subscriber connection would do the trick as well.

Thank you.

**Comment by sewenew** [comment]
@Cezero Thanks for your suggestion!

When connection is in subscribing mode, it's restricted, and can only call a few commands. So `Subscriber::set_name()` might be hard to be used correctly, since user must call it before `Subscriber` enters the subscribing mode.

I like the idea that making the connection name a part of `ConnectionOptions`. The only problem is that when connection pool is used, all connections in the pool will have the same name.

I'll try to implement this feature ASAP.

Regards

**Comment by Cezero** [comment]
Given that connections are established lazily, if the connection name is part of the ConnectionOptions, then I would think you could then set that on the subscriber connection prior to entering subscriber mode, safe in the knowledge that the "Redis" connection will never be established?

As for connection pool, you could append a number to connection name or something, such that you end up with ConnName-0, ConnName-1, ConnName-2 ... that would allow connections that are part of a pool to be easily grouped and yet still have unique identifiers.

**Comment by bronekrab** [comment]
Any news about this feature?

**Comment by sewenew** [comment]
The problem is that we still haven't decided how to distinguish different connections in the connection pool. If you have any suggestion or even better any clue on how do other client libraries implement this feature, feel free to let me know.

Also, I'll try to make a decision in the near future.

Regards

**Comment by bronekrab** [comment]
@sewenew Thanks for the reply!

Maybe just use one client name for all connections from the pool? Like the official redis-py library.

https://github.com/redis/redis-py/commit/dca7bd40a3a5d0c0853fe2befe706e214407697b

Regards

**Comment by sewenew** [comment]
I've implemented this feature, and as you suggested, all connections in the pool have the same name. You can test the latest code on master branch with the following code:

```
ConnectionOptions opts;
opts.host = "127.0.0.1";
opts.port = 6379;
opts.name = "name";
auto r = Redis(opts);
```

Sorry for the delay.

Regards
