### ISSUE TITLE
[QUESTION]TLS support for AWS Elasticache Cluster 

### ISSUE THREAD

**Issue by walkingerica** [sewenew/redis-plus-plus#332]
**Describe the problem**
We are using Redis Cluster in AWS Elasticache and trying to access it with redis-plus-plus. Now non-auth(TLS) cluster is accessed successfully, but auth cluster is failed to connect. It is handing there and without any errors, the command is "./build/test/test_redis++ -a  ***  -n clusterhost -c 6379". Any hints here, thank you!

During building the hiredis, we open TLS support as mentioned in the Readme. 
hiredis:
make USE_SSL=1
make USE_SSL=1 install

redisplusplus:
cmake -DREDIS_PLUS_PLUS_USE_TLS=ON -DREDIS_PLUS_PLUS_CXX_STANDARD=17 ..
make
make install 

**Environment:**
 - OS: [e.g. ubuntu]
 - Compiler: [e.g. gcc 7.5.0]
 - hiredis version: [latest]
 - redis-plus-plus version: [lastest]

**Comment by sewenew** [comment]
Sorry, but test_redis++ does not work with TLS.

You can write a simple code to do the test (check README for code example). Do not forget to specify certificate file related info.

Regards

**Comment by sewenew** [comment]
> Tried the sample code, but met the following errors. 

Looks like you did not link hiredis_ssl. In order to use TLS, you should link both hiredis and hiredis_ssl: `libhiredis.a`  and `libhiredis_ssl.a`, or `-lhiredis` and `-lhiredis_ssl`.

> The TLS needs certificate, but I am thinking it does not suit for Elasticache since the password is used instead of certificate.

So far, hiredis does not support skipping certificate verification. Since redis-plus-plus is based on hiredis, so it still needs a certificate file. Check [this](https://github.com/redis/hiredis/issues/927) for detail. 

Once hiredis has support for skipping certificate verification, redis-plus-plus will automatically support it. NO sure if hiredis already fix it. I'll do some research and might create a PR for hiredis in the near future.

Also, you might want to try the stunnel solution mentioned [here](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html). So that you don't need to make the client support TLS.

Regards

**Comment by walkingerica** [comment]
Thanks a lot, got you! 

> Looks like you did not link hiredis_ssl. In order to use TLS, you should link both hiredis and hiredis_ssl: libhiredis.a and libhiredis_ssl.a, or -lhiredis and -lhiredis_ssl.
--- I used actually.

Elasticache is using Auth/Password instead of certificate since its source is a reliable. I like to check if the Auth is supported by the RedisPlusPlus since I saw some hiredis examples are listed with Auth instead of certificate.

**Comment by sewenew** [comment]
If hiredis already has the support, redis-plus-plus should work too. Since it's based on hiredis.

Not sure if the example might use stunnel solution as I mentioned above.

Regards

**Comment by walkingerica** [comment]
> If hiredis already has the support, redis-plus-plus should work too. Since it's based on hiredis.
> 
> Not sure if the example might use stunnel solution as I mentioned above.
> 
> Regards

Samples from redis offcial https://docs.redis.com/latest/rs/references/client_references/client_c/  and huawei site https://support.huaweicloud.com/intl/en-us/usermanual-dcs/dcs-ug-0312010.html ，and they doesnot mention stunnel.

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
