### ISSUE TITLE
Can it support the ping、 pong command [FEATURE]

### ISSUE THREAD

**Issue by dandyhuang** [sewenew/redis-plus-plus#385]
first send command, The first request is time consuming。When the program is initialized, send the ping command，Then the request time will be reduced。

**Comment by dandyhuang** [comment]
> 

I use connection poll，  just want to reduce consuming on the first request。 There will be no problem with the next request。 but when service is restarted。especially cluster slot will all happen on the first。  I want Send a ping command, all slots are connected once

**Comment by dandyhuang** [comment]
> If you worry about the first request that might be slow, you can try the async interface. It might be a better solution for your case.
> 
> Regards

first I use connection pool AsyncRedisCluster。  I have tested, in the asynchronous case, the first request is very time consuming。in 10 Gigabit network card, smooth network, the simplest get hello world  command。  first cost 2ms， after cost 666us。like you said，lazily create connections reason。  so I want ，I need something like cluster info command。

**Comment by dandyhuang** [comment]
[QUESTION] Why are the auth, echo and ping commands not available for RedisCluster? #309
It may be difficult to achieve this, but I hope God@sewenew can make it happen

**Comment by dandyhuang** [comment]
> > If you worry about the first request that might be slow, you can try the async interface. It might be a better solution for your case.
> > Regards
> 
> first I use connection pool AsyncRedisCluster。 I have tested, in the asynchronous case, the first request is very time consuming。in 10 Gigabit network card, smooth network, the simplest get hello world command。 first cost 2ms， after cost 666us。like you said，lazily create connections reason。 so I want ，I need something like cluster info command。

[[QUESTION] Why are the auth, echo and ping commands not available for RedisCluster?](https://github.com/sewenew/redis-plus-plus/issues/309#top)
#309

It may be difficult to achieve this, but I hope God@sewenew can make it happen

**Comment by sewenew** [comment]
> I have tested, in the asynchronous case, the first request is very time consuming。in 10 Gigabit network card, smooth network, the simplest get hello world command。 first cost 2ms， after cost 666us

I checked the code, in order to avoid blocking to wait for slot-updating thread finishes updating slot info, redis-plus-plus initializes slot info with all slots assigned to the given node. Obviously, if you send command before slot-updating thread getting the slot info, redis-plus-plus might send command to an incorrect node, and gets redirected. That's be a time-consuming work. Check [the code](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/async_shards_pool.cpp#L42) for detail.

I'll try to find a way to optimize this behavior. If you have a better solution, feel free to let me know :)

I'm still not quite sure why you're so worry about the first request might be slow? Even if you can send PING to all nodes, when the connection is broken, or new nodes added to the cluster, redis-plus-plus will automatically reconnect, and you'll get this problem again. What's your exact scenario?

Sorry for the late reply. Too busy these days...

Regards

**Comment by dandyhuang** [comment]
thinks
