### ISSUE TITLE
[QUESTION] Getting error about hiredis whn trying to run cmake

### ISSUE THREAD

**Issue by ReturnHttp418** [sewenew/redis-plus-plus#400]
**Describe the problem**
Hi, I've successfully installed hiredis, but when trying to run `cmake  -DCMAKE_INSTALL_PREFIX=/usr/local/lib -DREDIS_PLUS_PLUS_CXX_STANDARD=11 ..` I got error as 

```
-- redis-plus-plus version: 1.3.5
-- redis-plus-plus build type: Release
-- redis-plus-plus build with CXX standard: c++11
-- redis-plus-plus TLS support: OFF
CMake Error at /mnt/c/project/hiredis-1.0.2/hiredis-1.0.2/hiredis-config.cmake:11 (message):
  File or directory /mnt/c/project/include referenced by variable
  hiredis_INCLUDEDIR does not exist !
Call Stack (most recent call first):
  /mnt/c/project/hiredis-1.0.2/hiredis-1.0.2/hiredis-config.cmake:27 (set_and_check)
  CMakeLists.txt:123 (find_package)
```

**Environment:**
 - OS: WSL2 ubuntu 
 - Compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
 - hiredis version: v1.0.2, master
 - redis-plus-plus version: master

**Additional context**
Can you help to take a look? Thanks!

**Comment by sewenew** [comment]
It seems that `-DCMAKE_INSTALL_PREFIX=` is incorrectly set.

If your hiredis is installed in */usr/local/include* (headers) and */usr/local/lib* (libraries), then you need to specify the path as follows:

```
-DCMAKE_INSTALL_PREFIX=/usr/local
```

Regards

**Comment by ReturnHttp418** [comment]
Hi @sewenew 
Thanks for replying to me so quickly. However, I still got the same error using `cmake  -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_PREFIX=/usr/local -DREDIS_PLUS_PLUS_CXX_STANDARD=11 ..`.
The variable of my CMakeSettings.json is defined as:
```
 "variables": [
                {
                    "name": "HIREDIS_HEADER",
                    "value": "/usr/local/include/hiredis",
                    "type": "PATH"
                },
                {
                    "name": "HIREDIS_LIB",
                    "value": "/usr/local/lib/libhiredis.so",
                    "type": "FILEPATH"
                },
                {
                    "name": "TEST_HIREDIS_LIB",
                    "value": "/usr/local/lib/libhiredis.so",
                    "type": "FILEPATH"
                }
```

**Comment by sewenew** [comment]
How did you installed hiredis? With the make command or cmake? The following error message seems that you used incorrect hiredis path:

> CMake Error at /mnt/c/project/hiredis-1.0.2/hiredis-1.0.2/hiredis-config.cmake:11 (message):
  File or directory /mnt/c/project/include referenced by variable
  hiredis_INCLUDEDIR does not exist !

Looks like you installed hiredis with cmake (hiredis-config.cmake), and the installation header path is */mnt/c/project/include*. However, you try to set hiredis path as */usr/local*. So what's exactly the path that you installed hiredis?

If you installed it to /usr/local, please check if there's header and libs for hiredis under /usr/local. If you installed it in  /mnt/c/project/, also do the check.

NOTE: never install multiple hiredis, since it will cause some wired problems. Ensure you only have one and only hiredis installed.

Regards

**Comment by ReturnHttp418** [comment]
Hi,
I've finally made it work by removing the whole build directory and recreate and remake everything. It seems that it used some caches with wrong path value that keep causing this error. Thanks for your quick response!
Cheers,
