### ISSUE TITLE
[QUESTION] Failed to insert data into Redis Cluster

### ISSUE THREAD

**Issue by burningCnn** [sewenew/redis-plus-plus#413]
Hallo:

    I wanted to insert data into a redis cluster which contains three master nodes、thress slave nodes.
    code:
   `ConnectionOptions connection_options;
        connection_options.connect_timeout = std::chrono::milliseconds(50000);
        connection_options.socket_timeout = std::chrono::milliseconds(50000);
        connection_options.host = _redis_nodes[0].first;
        connection_options.port = _redis_nodes[0].second;
        connection_options.password = _passwd;
        _redis = new RedisCluster(connection_options);

    void redis_cluster::mset(std::vector<std::pair<std::string, std::string>>* records)
    {
        _redis->mset(records->begin(), records->end());
    }
`

throw exception : Failed to send command with key: fm:trival:rival_code=5575

I use Redis CLI to check that there is no problem with the Redis cluster
redis is deployed on windows,redis-plus-plus on redhat

**Comment by sewenew** [comment]
First of all, please ensure all keys in `records` are hashed to the same slot, e.g. has the same hash tag. Otherwise, you cannot set them with `mset`.

Secondly, please check if the cluster is stable, if some slots are moving from one node to another node, and the source node has already run `CLUSTER SETSLOT` command, while the destination does not run it, you'll get this error message. In this case, you can retry the operation, and when the cluster is stable, everything will be fine.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
