### ISSUE TITLE
[QUESTION]Is it necessary for single-threaded code to use connection pooling?

### ISSUE THREAD

**Issue by lxycomeon** [sewenew/redis-plus-plus#415]
If my code runs in a single thread using the redis++ async API, is it more efficient to use a connection pool. why in my test, the used connections is always one?

**Comment by sewenew** [comment]
First of all, AsyncRedis always uses a connection pool to manage connections, although by default, i.e. without `ConnectionPoolOptions` set, the pool size is 1.

If your code is single-threaded, you don't need to make the pool size larger than 1. Since everything is single-threaded, only one connection will be used.

Regards

**Comment by lxycomeon** [comment]
Whether the interface of the callback function is also called by the main thread？
So for a single thread, I can think that the execution order of the callback functions is the same as the order of calling the asynchronous interface？

**Comment by sewenew** [comment]
> Whether the interface of the callback function is also called by the main thread？

No. There's a dedicated thread running the event loop, and the callbacks are run in that thread.

> for a single thread, I can think that the execution order of the callback functions is the same as the order of calling the asynchronous interface？

YES, with the current implementation, if I remember correctly. However, I'd suggest that you do not depend on it. Since the implementation might be changed in the future. And your code might also change to use multiple-threading in the future.

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
