### ISSUE TITLE
Polymorphism between Redis and RedisCluster

### ISSUE THREAD

**Issue by bigsamich** [sewenew/redis-plus-plus#450]
I have an adapter class which can use a Redis Connection or RedisCluster connection.
Right now the way i handle this is via a template or by having a discreet adapter classes. 
One that holds a redis object, the other a rediscluster object.

Is there a better way to handle this?
Can I just use RedisCluster for a single node instance?

It doesnt appear that redis and rediscluster use a common base class.
Id like to avoid writing some abstract class with a factory.

Thanks in advance

**Comment by sewenew** [comment]
> Can I just use RedisCluster for a single node instance?

No, you cannot do that. RedisCluster sends commands to Redis Cluster to get cluster info. If you use RedisCluster to connect to a single node instance, it fails to get those info, and cannot work correctly.

> It doesnt appear that redis and rediscluster use a common base class.

Because `RedisCluster` and `Redis` support some commands in different ways, e.g. `PING`, `INFO`.

> Is there a better way to handle this?

If you only need common commands between `RedisCluster` and `Redis`, you can have a base class for your wrapper, and create a template subclass for `RedisCluster` and `Redis`.

```
class Wrapper {
public:
  virtual ~Wrapper() = default;

  virtual OptionalString get(const StringView &key) = 0;
};

template <typename T>
class WrapperTpl : public Wrapper {
public:
  WrapperTpl(const StringView &uri) : _instance(uri) {} 

  OptionalString get(const StringView &key) override {
    return _instance.get(key);
  }

private:
  T _instance;
};
```

Regards

**Comment by sewenew** [comment]
Since there's no update, I'll close this issue.

Regards
