### ISSUE TITLE
[FEATURE] Allow specifying the keepalive interval  

### ISSUE THREAD

**Issue by wb2712** [sewenew/redis-plus-plus#453]
hiredis
Allow specifying the keepalive interval #1168

**Comment by sewenew** [comment]
Thanks for the suggestion! I'll take a look on how to implement it. It seems not an easy fix, since we need to ensure the code can work compatibly with old version of hiredis, i.e. hiredis without such an interface.

I'll let you know, if I get some progress.

Regrads

**Comment by sewenew** [comment]
I've added support for this feature. You can try the latest code on **dev** branch. Also you should install the latest hiredis on master branch to have this support.

Since this is a new API for hiredis, I need to use cmake to check if this feature is supported, and dynamically create a `hiredis_features.h` which includes some feature testing macro. Not sure if this is the best way to make the code compatible with hiredis of any version. So I need to make some more tests and do some more research before merging the code into master branch. If you have any feedback on the implementation, feel free to let me know :)

Sorry for the late reply, too busy these days...

Regards

**Comment by sewenew** [comment]
Code has been merged into master branch.

Regards
