### ISSUE TITLE
[FEATURE]Enable hiredis with ssl support on Windows

### ISSUE THREAD

**Issue by jbrezina** [sewenew/redis-plus-plus#495]
hiredis [was updated to version 1.1.0](https://github.com/microsoft/vcpkg/issues/30044) and supports ssl. I tested it on Windows using vcpkg with enabled ssl feature. Would it be possible to provide this behavior for redis-plus-plus on Windows?

**Comment by sewenew** [comment]
redis-plus-plus can work with hiredis v1.1.0. You can update hiredis to v1.1.0, and reinstall redis-plus-plus to depends on this new version.

Or, do you want to have a new version of redis-plus-plus on vcpkg that depends on new version of hiredis? In that case, you'd better create an issue on vcpkg. Because I'm not familiar with vcpkg, and not the maintainer. Sorry for that...

Also, old version of hiredis DOES support SSL on Windows. The new version of hiredis have some feature enhancement. If you don't need these new features, you can use the old version.

Regards
