### ISSUE TITLE
Issue with the connection pool

### ISSUE THREAD

**Issue by ksalamat** [sewenew/redis-plus-plus#54]
Hi,

many thanks for the great library ! I have got to this weird problem. I have an application with a lot of interaction with redis. Most of my interaction are through pipeline. I use the connection pool with 30 connections and I have set the keepalive option to true.  However I have still a lot of IN_WAIT TCP connection and I have "Failed to connect to Redis: Cannot assign requested address" errors that are resulting from the port space becoming full. I do not understand why the pool is not used. 

Here is my code for generating the connection 
Redis *bgpRedisConnect(string host, int port, int dbase){
    try {
        ConnectionOptions connection_options;
        connection_options.host = host;  // Required.
        connection_options.port = port; // Optional. The default port is 6379.
        connection_options.db = dbase;// Optional. Use the 0th database by default.
        connection_options.keep_alive=true;
//        connection_options.type = ConnectionType::UNIX;
//        connection_options.path = "/var/run/redis/redis.sock";

        // Optional. Timeout before we successfully send request to or receive response from redis.
        // By default, the timeout is 0ms, i.e. never timeout and block until we send or receive successfuly.
        // NOTE: if any command is timed out, we throw a TimeoutError exception.
//        connection_options.socket_timeout = std::chrono::milliseconds(500);

        ConnectionPoolOptions pool_options;
        pool_options.size = 30;  // Pool size, i.e. max number of connections.

        // Create an Redis object, which is movable but NOT copyable.
        return new Redis(connection_options, pool_options);
    } catch (const Error &e) {
        std::cout<<"Redis connection error:"<<e.what()<<endl;
        return NULL;            // Error handling.
    }
}

I thereafter reuse this same connection is several thread (16). 

Many thanks for your help.

**Comment by sewenew** [comment]
Hi @ksalamat 

When you create a pipeline with `Redis::pipeline()` method, [it will create a new connection](https://github.com/sewenew/redis-plus-plus#create-pipeline), instead of picking a connection from the underlying connection pool. So you should reuse the `Pipeline` object, instead of creating it again and again. It's NOT a cheap operation.

You might wonder why not pick a connection from the pool when creating a `Pipeline`, `Transaction` and `Subscriber`. Because I worried that user might create lots of `Pipeline` objects, and forget to destroy it. Then the connection pool will be empty.

However, there's a plan to add a boolean parameter for the `Redis::pipeline()` method to let user decide whether picking a connection from pool or creating a new one. When this is done, I'll let you know.

If you still have any problem on *redis-plus-plus*, feel free to let me know :)

Regards

**Comment by sewenew** [comment]
Hi @ksalamat 

Now, redis-plus-plus supports creating pipeline with connection from the underlying pool. Please check [the doc](https://github.com/sewenew/redis-plus-plus#create-pipeline-without-creating-new-connection) for detail.

Regards
