### ISSUE TITLE
[QUESTION] Approach for application code generically supporting Redis or RedisCluster

### ISSUE THREAD

**Issue by CJLove** [sewenew/redis-plus-plus#586]
**Describe the problem**
Thanks for a great library! As the README points out, the `RedisCluster` interface is very similar to the `Redis` interface with a few exceptions. That being said, these are two distinct concrete classes with no shared base, so application code using redis-plus-plus would need to choose one or the other. Are there any creative approaches folks have used to decouple application code from the Redis deployment architecture being used?

Thanks!

**Environment:**
 - OS: RHEL 8 Linux
 - Compiler: g++ 4.8.5, g++ 8.5.0
 - hiredis version: 1.2.0
 - redis-plus-plus version: 1.3.12

**Additional context**

**Comment by sewenew** [comment]
As you mentioned, `Redis` and `RedisCluster` interfaces are very similar, however, you cannot simply replace one for another. Since they have different behaviors, especially on multiple keys command.

Normally, if you are sure that you only need the common parts of `Redis` and `RedisCluster` interfaces, you can use template to make your application code works for both cases.

```
template <typename RedisInstance>
class App {
public:
  App(RedisInstance &&instance) : _instance(instance) {}

  void set(const string_view &key, const string_view &val) {
    _instance.set(key, value);
  }
private:
  RedisInstance _instance;
}
```

The [RedLock](https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis%2B%2B/patterns/redlock.h) and [test cases](https://github.com/sewenew/redis-plus-plus/blob/master/test/src/sw/redis%2B%2B/keys_cmds_test.h) use this pattern to make them work with both `Redis` and `RedisCluster`.

Regards
