### ISSUE TITLE
use Redis Cluster

### ISSUE THREAD

**Issue by gaofeia** [sewenew/redis-plus-plus#59]
code:

```
    SentinelOptions sentinel_opts;
    sentinel_opts.nodes = {{"20.200.45.227", 26379},
                           {"20.200.45.226", 26379},
                           {"20.200.45.228", 26379}};   // Required. List of Redis Sentinel nodes.

    sentinel_opts.password ="itc123";
    sentinel_opts.connect_timeout = std::chrono::milliseconds(200);
    sentinel_opts.socket_timeout = std::chrono::milliseconds(200);

    ConnectionOptions connection_opts;
    connection_opts.password = "itc123";  // Optional. No password by default.
    connection_opts.connect_timeout = std::chrono::milliseconds(100);   // Required.
    connection_opts.socket_timeout = std::chrono::milliseconds(100);    // Required.

    ConnectionPoolOptions pool_opts;
    pool_opts.size = 3; // Optional. The default size is 1.

    auto sentinel = std::make_shared<Sentinel>(sentinel_opts);;
    auto redis = Redis(sentinel, "sms", Role::MASTER, connection_opts, pool_opts);

    while(1)
    {
        OptionalStringPair pair;
        pair = redis.brpop("list:mt:61", 200);

       sleep(1);
   }
```

error:
terminate called after throwing an instance of 'sw::redis::Error'
  what():  Failed to create connection with sentinel
Aborted (core dumped)

Is there something wrong with my operation process?

**Comment by sewenew** [comment]
Hi @gaofeia 

First of all, since redis-plus-plus might throw exceptions, you always need to try-catch your code:

```
try {
    // your code here.
} catch (const sw::redis::Error &e) {
}
```

The error message you got, means that redis-plus-plus failed to connect to a sentinel, i.e. it has already tried to connect to all sentinels that you specified, but no one can be reached.

You can try to connect to these sentinels with the official *redis-cli*, and check if your sentinels are reachable. **NOTE**: you should try it on the same host that you run redis-plus-plus with the same connection options. If these sentinels are reachable, you code should work fine.

If you still have any problem, feel free to let me know.

Regards

**Comment by gaofeia** [comment]
I have a question. The port of redis is 6379 and the port of sentry mode is 26379. Which port should I connect to?No matter which one I connect to, I always report this error.Currently, I can use "redis-cli -h 20.200.45.226 -p 6379 -a itc123" to connect to redis, and "redis-cli -h 20.200.45.226 -p 26379 -a itc123" to connect to the sentry mode and check the sentinel status .

**Comment by gaofeia** [comment]
> Hi @gaofeia
> 
> First of all, since redis-plus-plus might throw exceptions, you always need to try-catch your code:
> 
> ```
> try {
>     // your code here.
> } catch (const sw::redis::Error &e) {
> }
> ```
> 
> The error message you got, means that redis-plus-plus failed to connect to a sentinel, i.e. it has already tried to connect to all sentinels that you specified, but no one can be reached.
> 
> You can try to connect to these sentinels with the official _redis-cli_, and check if your sentinels are reachable. **NOTE**: you should try it on the same host that you run redis-plus-plus with the same connection options. If these sentinels are reachable, you code should work fine.
> 
> If you still have any problem, feel free to let me know.
> 
> Regards

I have a question. The port of redis is 6379 and the port of sentry mode is 26379. Which port should I connect to?No matter which one I connect to, I always report this error.Currently, I can use "redis-cli -h 20.200.45.226 -p 6379 -a itc123" to connect to redis, and "redis-cli -h 20.200.45.226 -p 26379 -a itc123" to connect to the sentry mode and check the sentinel status .

**Comment by sewenew** [comment]
Hi @gaofeia 

> Why you got the error message?

I tried to reproduce your problem. And I have the following guess: *your sentinel is NOT authenticated with password*.

What's the version of your Redis and Sentinel? Only Redis 5.0 or latter support authentication. If your Redis is older than Redis 5.0, you cannot specify password when connecting to Redis. If your version is Redis 5.0 or latter, you still need to config Redis Sentinel to enable authentication by specifying *requirepass itc123* in *sentinel.conf*.

Can you try to connect to sentinel with the following command: *redis-cli -h 20.200.45.226 -p 26379*, i.e. not specifying the password. If you CAN login and run command with the sentinel, that means your sentinel has no password.

In this case, you don't need to specify a password with `sentinel_opts.password = itc123`. If you do, Redis Sentinel will refuse your connection, and that's why you got the error message: *Failed to create connection with sentinel*.

> The port of redis is 6379 and the port of sentry mode is 26379. Which port should I connect to?

You should connect to Redis sentinel's port: 26379.

> Is there any other problem?

Yes, there's another problem: **you need to specify a socket timeout for `ConnectionOptions` larger than the timeout you specified with `brpop`**.

Because with the current implementation, if the socket timeout is reached, the connection will be closed. However, you called `brpop` with 200 seconds, so if there's no item pushed to the list in 100ms (the socket timeout you specified), `brpop` will throw `TimeoutError` exception, and you might lose the message.


You can try the following modification, and see if it works:

```
    sentinel_opts.nodes = {{"20.200.45.227", 26379},     // <---- specify Redis Sentinel port
                           {"20.200.45.226", 26379},
                           {"20.200.45.228", 26379}};

    // sentinel_opts.password ="itc123";           <---- if your sentinel is not configured with password, DO NOT specify the password

    connection_opts.socket_timeout = std::chrono::seconds(2);    // <------- Socket timeout (2s) should larger than timeout specified with brpop (1s).

    while(1)
    {
        OptionalStringPair pair;
        pair = redis.brpop("list:mt:61", 1);    // <--------- Timeout specified with brpop (1s) should be less than the socket timeout (2s).

       sleep(1);
   }
```

If you still have any problem, feel free to let me know.

Regards

**Comment by gaofeia** [comment]
> Hi @gaofeia
> 
> > Why you got the error message?
> 
> I tried to reproduce your problem. And I have the following guess: _your sentinel is NOT authenticated with password_.
> 
> What's the version of your Redis and Sentinel? Only Redis 5.0 or latter support authentication. If your Redis is older than Redis 5.0, you cannot specify password when connecting to Redis. If your version is Redis 5.0 or latter, you still need to config Redis Sentinel to enable authentication by specifying _requirepass itc123_ in _sentinel.conf_.
> 
> Can you try to connect to sentinel with the following command: _redis-cli -h 20.200.45.226 -p 26379_, i.e. not specifying the password. If you CAN login and run command with the sentinel, that means your sentinel has no password.
> 
> In this case, you don't need to specify a password with `sentinel_opts.password = itc123`. If you do, Redis Sentinel will refuse your connection, and that's why you got the error message: _Failed to create connection with sentinel_.
> 
> > The port of redis is 6379 and the port of sentry mode is 26379. Which port should I connect to?
> 
> You should connect to Redis sentinel's port: 26379.
> 
> > Is there any other problem?
> 
> Yes, there's another problem: **you need to specify a socket timeout for `ConnectionOptions` larger than the timeout you specified with `brpop`**.
> 
> Because with the current implementation, if the socket timeout is reached, the connection will be closed. However, you called `brpop` with 200 seconds, so if there's no item pushed to the list in 100ms (the socket timeout you specified), `brpop` will throw `TimeoutError` exception, and you might lose the message.
> 
> You can try the following modification, and see if it works:
> 
> ```
>     sentinel_opts.nodes = {{"20.200.45.227", 26379},     // <---- specify Redis Sentinel port
>                            {"20.200.45.226", 26379},
>                            {"20.200.45.228", 26379}};
> 
>     // sentinel_opts.password ="itc123";           <---- if your sentinel is not configured with password, DO NOT specify the password
> 
>     connection_opts.socket_timeout = std::chrono::seconds(2);    // <------- Socket timeout (2s) should larger than timeout specified with brpop (1s).
> 
>     while(1)
>     {
>         OptionalStringPair pair;
>         pair = redis.brpop("list:mt:61", 1);    // <--------- Timeout specified with brpop (1s) should be less than the socket timeout (2s).
> 
>        sleep(1);
>    }
> ```
> 
> If you still have any problem, feel free to let me know.
> 
> Regards

thank you very much. This is the problem, no password is required to connect to the sentry. This is a test, and there are other problems in the follow-up development. I will ask you for help again.thank you very much.

**Comment by sewenew** [comment]
I'm glad that your problem is solved. If you have any problem with redis-plus-plus, feel free to let me know. If you like it, also feel free to star it :)

Regards

**Comment by gaofeia** [comment]
> 很高兴您的问题解决了。如果您对Redis Plus Plus有任何疑问，请随时告诉我。如果您喜欢它，也可以随时对其进行标记：)
> 
> 问候

ok，I will。Thank you again for your help。
