### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by cfryanr** [sewenew/redis-plus-plus#66]
Hi,

Great work on this library. We've started using it and it's been really nice so far. 😃 

Have you considered supporting TLS connections to Redis? hiredis supports it, and it looks like it might be a straightforward addition to redis-plus-plus. See https://github.com/redis/hiredis#ssltls-support

Thanks,
Ryan

**Comment by sewenew** [comment]
Hi @cfryanr 

Thanks for using using redis-plus-plus!

YES, there's a plan to support TLS as a part of supporting Redis 6.0 which supports SSL natively. If I have any progress on it, I'll let you know :)

Regards

**Comment by mruki** [comment]
+1 for TLS support. @cfryanr if it's in hiredis, which is a dependency to this project, then does it mean it could be feasible to enable it this way without waiting for support in redis++?

**Comment by sewenew** [comment]
Guys, sorry for the delay.

I'm busy with another issue and other stuffs these days. I'll try this feature ASAP.

Regards

**Comment by cfryanr** [comment]
@mruki Not in any obvious way. Redis plus plus doesn't seem to offer any hooks to allow the user of the library to override the way that the hiredis library is called under the hood to create/close the connection or send data over the connection.

Thanks for offering to work on this soon, @sewenew!

**Comment by sewenew** [comment]
Guys, I've added TLS support to redis-plus-plus. You can fetch the latest code on [ssl branch](https://github.com/sewenew/redis-plus-plus/tree/ssl), and have a try.

I did some tests and it works fine. However, I still need to do more tests, and not sure if the API will be changed in the future (since hiredis just [changed its SSL API](https://github.com/redis/hiredis/commit/190bca88d0635f1e53d9e39fc69f4f21b67a1baf#diff-5931449ee480a798cabbfe5a0df96da8) on 25 May 2020, not sure if it's already stable).

In order to enable TLS, you need to [build the latest hiredis with SSL support](https://github.com/redis/hiredis#ssltls-support), and build redis-plus-plus with `-DREDIS_PLUS_PLUS_USE_TLS=ON` option when running cmake:

```
cmake -DCMAKE_PREFIX_PATH=/path/to/hiredis-ssl -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/path/to/instal/dirl -DREDIS_PLUS_PLUS_USE_TLS=ON ..
```

The following is an example on how to use it:

```
ConnectionOptions opts;
opts.host = "127.0.0.1";
opts.port = 6379;

// enable TLS
opts.tls_enabled = true;

// set TLS options. These options are the same as redis-cli's TLS options.
// You can run `redis-cli --help` to check the explanation of these options.
opts.tls_options.cacert = "CA Certificate file to verify with";
opts.tls_options.cert = "Client certificate to authenticate with";
opts.tls_options.key = "Private key file to authenticate with";

auto redis = Redis(opts);

cout << redis.ping() << endl;
```

If you have any problem on it, feel free to let me know.

Regards

**Comment by mruki** [comment]
Thanks. Change looks really good.
I couldn't wait for it, so last week I introduced TLS myself as well (slightly different than you), but it also worked :) 

The only little remark I have about your commit is that in line 64 in tls.cpp you can retrieve an error description from the context and add it to an exception message. It's a detail, but could help debugging.

BR,
Konrad

**Comment by sewenew** [comment]
Hi @mruki 

I modified the interface of setting TLS options, and also optimize the CMakeLists.txt file so that end user doesn't need to specify `-DREDIS_PLUS_PLUS_USE_TLS` when s/he builds application code.

I've updated the example of my last comment, and you can take a look. Also you can check the [doc](https://github.com/sewenew/redis-plus-plus/tree/ssl#tlsssl-support) for detail.

Regards

**Comment by mruki** [comment]
thanks @sewenew 
sorry for a delay, but I spent some of this time for testing the new feature and it seems to be working!
If you're curious, environment I used was: client on windows, built with VS2015, x64 connected to Redis Enterprise version 5. Soon I will have an option to test it against Redis 6 too.
I'll take your fresh changes now and see if they work too - any plans on merging to master and tagging?

Thanks!
Konrad

**Comment by sewenew** [comment]
Hi @mruki 

Thanks for your testing!

> any plans on merging to master and tagging?

As I mentioned that I'm not sure if hiredis' API is already steady. So I'd like to keep it on the ssl branch for a while. If there're any changes on master branch, I'll merge it to this branch to ensure it has the latest features.

Also I'll keep this issue open until the code being merged into master.

Thanks again for your work!

Regards

**Comment by mruki** [comment]
No worries and thanks for a reply.
I have tested the new implementation as well  - works very well, both in terms of build and runtime.

BR,
Konrad

**Comment by vchinta15** [comment]
Hi @sewenew,

Is TLS support still only on the ssl branch or has it been merged back to master? I'm a newbie to Redis and have been looking around for a good C++ Redis library. I prefer this library but TLS/SSL support is required for the Redis project I need to work on. Please let me know the latest status.

Regards.

**Comment by sewenew** [comment]
Hi @vchinta15 

Since hiredis already released 1.0.0 with TLS support recently, I think the API is stable now. I'll merge the ssl branch into master this week. Because redis-plus-plus has some major change in connection management since the ssl branch, I need to do some more test. I'll let you know, when I finish these work.

Regards

**Comment by vchinta15** [comment]
> Hi @vchinta15
> 
> Since hiredis already released 1.0.0 with TLS support recently, I think the API is stable now. I'll merge the ssl branch into master this week. Because redis-plus-plus has some major change in connection management since the ssl branch, I need to do some more test. I'll let you know, when I finish these work.
> 
> Regards

Thanks @sewenew . I'll touch base with you early next week. 

Regards.

**Comment by sewenew** [comment]
Hi Guys, 

ssl branch has been merged into master branch. If you have any problem on TLS support, feel free to let me know.

Regards

**Comment by mruki** [comment]
@sewenew thanks for info about the merge. Could you please point me to information what sort of connection management changes were there on master?
Was about to create an issue here anyway about a similar topic. Some time ago I ran a test, where one of the cluster's node was restarted to see if redis-plus-plus would refresh the topology. Unfortunately it didn't go ok.
Code failed at https://github.com/sewenew/redis-plus-plus/blob/master/src/sw/redis++/redis_cluster.hpp#L1332 - the problem was that it wasn't even able to send the CLUSTER SLOTS command.

Scenario description:
Redis enterprise 6.0.6-36
Regular DB with 2 shards and standard hashing policy
redis++ client fails to update list of nodes if a shard is migrated to another node (manually or during failover)

Any chance this is something fixed in the meantime?

Thanks!

**Comment by sewenew** [comment]
@mruki The connection management changes have nothing to do with cluster management, instead it tries to support creating pipeline and transaction without creating new connection.

Also I created a new issue to track the problem.

Regards

**Comment by mruki** [comment]
ok thanks so much @sewenew
