### ISSUE TITLE
Support RESP3 protocol

### ISSUE THREAD

**Issue by sewenew** [sewenew/redis-plus-plus#86]

**Comment by wingunder** [comment]
Hi @sewenew,

It seems as if the `hiredis` `redisSetPushCallback` call is not being used in `redis-plus-plus`. It however seems as if this call only works with RESP3, and that's why I'm adding this comment to this issue. 

Adding the functionality of this callback to `redis-plus-plus` would certainly help with some pub/sub issues that are coming from the user-base at the moment.

Disclaimer: This post is not a request, just a place-holder for less busy times.

Regards

**Comment by sewenew** [comment]
@wingunder Thanks for the suggestion!

I did some rough research on this `PUSH` feature. It needs Redis 6.0 and higher version of hiredis support. Also if it's used with synchronous API, client code still has to do a loop for these messages, and it cannot solve those pub/sub issues. Correct me if I'm wrong :)

I think those pub/sub issues might be solved by asynchronous API, however, so far, I still do not find a good API design for pub/sub's asynchronous API.

Regards
