### ISSUE TITLE
Error streaming relatively large amount of data

### ISSUE THREAD

**Issue by surygeng** [sewenew/redis-plus-plus#90]
Hi. I am using xadd commend to stream 5.5 MiB data but gets this error "Failed to get reply: Connection reset by peer" on Debian and "Failed to get reply: Protocol wrong type for socket" on macOS. Here is the same piece of code.

```
#include <iostream>
#include <vector>
#include <sw/redis++/redis++.h>

using namespace sw::redis;
using namespace std;

int main(){
	
	int num = 5760000;  // cannot handle data size large like this?

	vector<int> attrs;
	for(int i = 0; i < num; i++){
	attrs.push_back(i);
	}
	cout << "data created" << endl;
	
	for (int j = 0;j!=10; j++){
	  try {
	
	ConnectionOptions connection_options;
	connection_options.host = "127.0.0.1";
	connection_options.port = 6379; // Optional. The default port is 6379.
        // connection_options.socket_timeout = chrono::milliseconds(200000);

	Redis redis(connection_options);	

	// Add an item into the stream. This method returns the auto generated id.
	auto id = redis.xadd("data-kevin", "*", attrs.begin(), attrs.end() );

	}catch (const Error &e) {
          // Error handling.
          cout << "stream failed: " ;
          cerr << e.what() << endl;
}
}
	
	return 0;
}
```

I use compile command like this: g++ -std=c++11 -o app app.cpp -lredis++ -lhiredis 

Any suggestion is welcomed.

**Comment by sewenew** [comment]
@surygeng You CANNOT send so many, i.e. `5760000 / 2`, <field, value> pairs with `XADD` command.

The max number of arguments for each Redis command is `1024 * 1024`. If you send too many arguments, Redis will refuse your request.

The prototype of `XADD` command is as follows:

```
XADD key ID field value [field value ...]
```

So the max size of your `attrs` vector is: `1024 * 1024 - 4`. Because `XADD key ID` counts 3, and field-value must be paired.

> Python code tested to be working in both environments, even with more than 5.5 MiB data size.

I doubt it. I think Python client cannot send so many <field, value> pairs with XADD command either.

> I believe redis can handle a max of 512MB.

Yes, the value size of Redis string is 512M. But it has nothing to do with this problem.

**NOTE**: Also it's always a bad idea to send so many data to Redis in a single command, since Redis is single-threaded, it might block Redis for a long time.

Regards

**Comment by surygeng** [comment]
I understand the problem now. I meant to stream a number of values not {field, value} pairs. I misused the command. Thank you for your clarification!
