### ISSUE TITLE
Is there any way to check the status of the Pipeline?

### ISSUE THREAD

**Issue by nqf** [sewenew/redis-plus-plus#95]
If any of Pipeline's method throws an exception other than ReplyError, the Pipeline object enters an invalid state. You CANNOT use it any more, but only destroy the object, and create a new one.

I want to check the status of the pipe， Is there a way like this（pipe.is_broken()）?

**Comment by sewenew** [comment]
@nqf There's no way to do that. If the Pipeline object throws an error other than ReplyError, you should not use it any more, otherwise, the behavior is undefined.

Why you need to check the status of a pipeline?

Regards

**Comment by nqf** [comment]
@sewenew  Thank you very much for your answer， Because I have an `connect_pool<pipe> `in my application, So I want to check the status of the pipe， If the pipe is broken, it will automatically re create a pipe

**Comment by sewenew** [comment]
@nqf There're two ways to achieve that. When you get an exception, remove the pipeline from the pool, create a new one and move it into the pool.

However, since the latest code supports [creating pipeline from the underlying connection pool](https://github.com/sewenew/redis-plus-plus#create-pipeline-without-creating-new-connection), you no longer need to maintain a pool by yourself. Instead you can create pipeline with much cheaper operations.

Also read the doc carefully before using this feature, to avoid bad performance or even dead lock. If you have any problem on this feature, feel free to let me know.

Regards
