### ISSUE TITLE
how to send a single parameter command by command api?

### ISSUE THREAD

**Issue by gbuniv** [sewenew/redis-plus-plus#96]
like redis.command("multi");,it compile error.

**Comment by sewenew** [comment]
@gbuniv First of all, if you want to Use Redis transaction, you don't need to send MULTI command by yourself. Instead, you can create `Transaction` object, which will send the MULTI command automatically. Check the [doc](https://github.com/sewenew/redis-plus-plus#transaction) for detail.

> like redis.command("multi");,it compile error.

Can you show me the error message?

Normally, you can use the [generic command interface](https://github.com/sewenew/redis-plus-plus#generic-command-interface) to send the command:

```
template <typename Result, typename ...Args>
Result command(const StringView &cmd_name, Args &&...args);
```

This method is a template, you should also specify the type of return value. Take the `PING` command for an example. Since the return value of `PING` command is a string, we specify the return type as `std::string`:

```
auto pong = command<std::string>("ping");
```

Regards

**Comment by gbuniv** [comment]
@sewenew thanks for yours response first, i call redis.command("multi") . then error like this：
main.cc:62:34: error: no matching function for call to ‘sw::redis::RedisCluster::command(const char [6])’
       redis_impl->command("multi");
                                  ^
main.cc:62:34: note: candidates are:
In file included from /data/svr/morty/audio/thirdparty/redis-plus-plus/include/sw/redis++/redis++.h:21:0,
                 from redis_cluster_imp.h:3,
                 from main.cc:19:
/data/svr/morty/audio/thirdparty/redis-plus-plus/include/sw/redis++/redis_cluster.h:70:10: note: template<class Cmd, class Key, class ... Args> typename std::enable_if<(! std::is_convertible<Iter, sw::redis::StringView>::value), std::unique_ptr<redisReply, sw::redis::ReplyDeleter> >::type sw::redis::RedisCluster::command(Cmd, Key&&, Args&& ...)
     auto command(Cmd cmd, Key &&key, Args &&...args)
          ^
/data/svr/morty/audio/thirdparty/redis-plus-plus/include/sw/redis++/redis_cluster.h:70:10: note:   template argument deduction/substitution failed:
main.cc:62:34: note:   candidate expects 3 arguments, 1 provided
       redis_impl->command("multi");
                                  ^
In file included from /data/svr/morty/audio/thirdparty/redis-plus-plus/include/sw/redis++/redis++.h:21:0,
                 from redis_cluster_imp.h:3,
                 from main.cc:19:
/data/svr/morty/audio/thirdparty/redis-plus-plus/include/sw/redis++/redis_cluster.h:74:10: note: template<class Key, class ... Args> typename std::enable_if<((std::is_convertible<Iter, sw::redis::StringView>::value || std::is_arithmetic<typename std::decay<_Tp>::type>::value) && (! sw::redis::IsIter<typename sw::redis::LastType<Key, Args ...>::type>::value)), std::unique_ptr<redisReply, sw::redis::ReplyDeleter> >::type sw::redis::RedisCluster::command(const sw::redis::StringView&, Key&&, Args&& ...)
     auto command(const StringView &cmd_name, Key &&key, Args &&...args)
          ^
/data/svr/morty/audio/thirdparty/redis-plus-plus/include/sw/redis++/redis_cluster.h:74:10: note:   template argument deduction/substitution failed:
main.cc:62:34: note:   candidate expects 3 arguments, 1 provided
       redis_impl->command("multi");

**Comment by sewenew** [comment]
@gbuniv So you are using RedisCluster? If you do, you need to create a Redis object with the RedisCluster object to send the command. Check the [doc](https://github.com/sewenew/redis-plus-plus#interfaces) for detail.

`auto r = cluster.Redis(“hashtag”); auto pong = r.command<string>(“ping”);`

Again, instead of send multi command manually, you should create a Transaction object with RedisCluster: `auto tx = cluster.transaction(“hashtag”);` Check the [doc](https://github.com/sewenew/redis-plus-plus#pipeline-and-transaction) for detail.

**Comment by gbuniv** [comment]
yeah,i using Transaction now,thanks.
